version: "2"

services: 
  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "33060:3306"
    volumes:
      - ./mysql57:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ssm
      - MYSQL_ROOT_PASSWORD=root
